# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=150)),
                ('fprice', models.FloatField()),
                ('dtype', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
