# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u83dc\u540d')),
                ('image', models.ImageField(default='dish/%Y/%m', upload_to=b'', verbose_name='\u56fe\u7247')),
                ('price', models.FloatField(verbose_name='\u4ef7\u683c')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('recipe', models.TextField(verbose_name='\u70f9\u996a\u65b9\u6cd5')),
                ('sales', models.IntegerField(default=0, verbose_name='\u9500\u552e\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u83dc\u54c1',
                'verbose_name_plural': '\u83dc\u54c1',
            },
        ),
        migrations.CreateModel(
            name='DishesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u83dc\u54c1\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u83dc\u54c1\u7c7b\u522b',
                'verbose_name_plural': '\u83dc\u54c1\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='\u603b\u4ef7')),
                ('dishes', models.ManyToManyField(to='orderApp.Dish', verbose_name='\u83dc\u54c1')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderApp.DishesType', verbose_name='\u83dc\u54c1\u7c7b\u522b'),
        ),
    ]
