# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-24 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dish/%Y/%m', verbose_name='\u56fe\u7247'),
        ),
    ]
