# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
