# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_auto_20170101_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dimage',
            field=models.ImageField(default='/home/liqingqing/\u56fe\u7247/1.jpg', upload_to=b''),
        ),
    ]
