# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderApp', '0002_auto_20170524_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderApp.Dish', verbose_name='\u83dc\u54c1'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='\u83dc\u54c1\u6570\u91cf'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u5355\u4ef7'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
