# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_auto_20170525_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
    ]
