# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to=b'')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.orderApp.Dish')),
            ],
        ),
    ]
